import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Bookmark, Check, CheckCircle2, Clock3, Highlighter, Minus, Plus, Search, Sparkles, X } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { examples, resultsFor, type Book } from "@/lib/mock-data";
import { useOnboarding } from "@/lib/onboarding-context";

export function Logo() {
  return <Link to="/" className="font-ui text-xl font-extrabold text-foreground focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring">Perlego<span className="text-primary">.</span></Link>;
}

export function Header({ back }: { back?: "/" | "/results" }) {
  return <header className="mx-auto flex h-18 w-full max-w-7xl items-center justify-between px-5 sm:px-8">
    <div className="flex items-center gap-5">{back ? <Link to={back} aria-label="Go back" className="grid size-10 place-items-center rounded-md hover:bg-muted focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring"><ArrowLeft size={20} /></Link> : null}<Logo /></div>
    <button className="text-sm font-semibold text-foreground underline decoration-border underline-offset-4 hover:text-primary">Log in</button>
  </header>;
}

export function SearchHome() {
  const { query, setQuery } = useOnboarding();
  const [value, setValue] = useState(query);
  const navigate = useNavigate();
  const submit = (event?: FormEvent) => { event?.preventDefault(); if (!value.trim()) return; setQuery(value.trim()); navigate({ to: "/results" }); };
  return <main className="min-h-screen bg-paper">
    <Header />
    <section className="mx-auto flex min-h-[calc(100vh-72px)] max-w-5xl flex-col items-center px-5 pt-[11vh] text-center sm:px-8">
      <div className="mb-7 inline-flex items-center gap-2 rounded-full bg-primary-soft px-3 py-1.5 text-sm font-semibold text-primary"><Sparkles size={15} /> AI-powered study search</div>
      <h1 className="max-w-4xl font-display text-5xl leading-[1.03] sm:text-7xl">Exam coming up? Find exactly what to revise.</h1>
      <p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Tell us your module or topics. We’ll find the chapters that matter, so you can start with confidence.</p>
      <form onSubmit={submit} className="mt-10 flex w-full max-w-3xl items-center gap-2 rounded-lg border border-input bg-background p-2 shadow-warm focus-within:ring-4 focus-within:ring-ring">
        <Search className="ml-3 shrink-0 text-muted-foreground" size={22} />
        <label className="sr-only" htmlFor="study-search">What do you need to revise?</label>
        <input id="study-search" value={value} onChange={(e) => setValue(e.target.value)} className="min-w-0 flex-1 bg-transparent px-2 py-3 text-base outline-none sm:text-lg" placeholder="Enter your exam topics…" />
        <Button type="submit" size="lg" className="hidden sm:inline-flex">Find my chapters <ArrowRight size={18} /></Button>
        <Button type="submit" size="icon" aria-label="Find my chapters" className="sm:hidden"><ArrowRight size={18} /></Button>
      </form>
      <div className="mt-7 flex max-w-4xl flex-wrap justify-center gap-2.5">{examples.map((example) => <button key={example} onClick={() => { setValue(example); setQuery(example); navigate({ to: "/results" }); }} className="rounded-full border border-border bg-background px-4 py-2.5 text-left text-sm text-secondary-foreground transition hover:border-primary hover:text-primary focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring">{example}</button>)}</div>
      <p className="mt-10 flex items-center gap-2 text-sm text-muted-foreground"><Check size={16} className="text-success" /> No account needed to see your matches</p>
    </section>
  </main>;
}

function Cover({ book, small = false }: { book: Book; small?: boolean }) {
  return <div className={cn("book-cover relative shrink-0 overflow-hidden rounded-sm p-3 text-left shadow-warm", `cover-${book.cover}`, small ? "h-32 w-[86px]" : "h-48 w-32")} aria-hidden="true"><div className="absolute inset-y-0 left-3 w-px bg-foreground/15"/><p className="relative ml-2 font-display text-lg leading-tight text-foreground">{book.title}</p><p className="relative ml-2 mt-3 text-[10px] font-bold uppercase text-foreground/70">{book.author}</p></div>;
}

export function ResultsPage() {
  const { query, selectBook } = useOnboarding();
  const set = resultsFor(query);
  const [loading, setLoading] = useState(true);
  const [preview, setPreview] = useState<Book | null>(null);
  const navigate = useNavigate();
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 1500); return () => window.clearTimeout(timer); }, [query]);
  const choose = (book: Book) => { selectBook(book); navigate({ to: "/signup" }); };
  return <main className="min-h-screen bg-paper"><Header back="/" /><section className="mx-auto max-w-7xl px-5 pb-20 pt-8 sm:px-8">
    <p className="text-sm font-semibold text-primary">Your study matches</p><h1 className="mt-2 max-w-4xl font-display text-4xl sm:text-5xl">The fastest route through “{query}”</h1>
    {loading ? <LoadingResults /> : <><div className="mt-7 flex items-start gap-3 border-y border-border py-5 text-base"><Sparkles className="mt-0.5 shrink-0 text-primary" size={20}/><p>I found 3 books covering all {set.books[0]?.topics.length ?? 3} of your topics. Start with <strong>#1</strong> for the clearest route.</p></div>
    <div className="mt-7 grid gap-5">{set.books.map((book, index) => <article key={book.id} className="result-card grid gap-6 rounded-lg border border-border bg-background p-5 transition hover:-translate-y-0.5 hover:shadow-warm-lg sm:grid-cols-[128px_1fr_auto] sm:p-6">
      <Cover book={book}/><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary-soft px-2.5 py-1 text-xs font-bold text-primary">{book.match}% match</span>{index === 0 && <span className="rounded-full bg-success-soft px-2.5 py-1 text-xs font-bold text-success">Best place to start</span>}</div><h2 className="mt-3 font-ui text-xl font-bold">{book.title}</h2><p className="mt-1 text-sm text-muted-foreground">{book.author} · {book.edition}</p>
      <div className="mt-5 grid gap-2">{book.chapters.map((chapter) => <div key={chapter.number} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span><strong>Chapter {chapter.number}</strong> · {chapter.title}</span><span className="text-muted-foreground">pp. {chapter.pages}</span></div>)}</div>
      <p className="mt-5 text-xs font-bold uppercase text-muted-foreground">Topics covered</p><div className="mt-2 flex flex-wrap gap-2">{book.topics.map((topic) => <span key={topic.label} className={cn("rounded-full px-2.5 py-1 text-xs font-medium", topic.covered ? "bg-success-soft text-success" : "bg-muted text-muted-foreground")}><span aria-hidden="true">{topic.covered ? "✓" : "×"}</span> {topic.label}</span>)}</div></div>
      <div className="flex min-w-44 flex-col justify-between gap-5 border-t border-border pt-5 sm:border-l sm:border-t-0 sm:pl-6 sm:pt-0"><p className="flex items-center gap-2 text-sm text-muted-foreground"><Clock3 size={17}/> {book.chapters.reduce((n, c) => n + c.minutes, 0)} min reading</p><div className="grid gap-2"><Button onClick={() => choose(book)}>Start studying <ArrowRight size={17}/></Button><Button variant="ghost" onClick={() => { selectBook(book); setPreview(book); }}>Preview chapter</Button></div></div>
    </article>)}</div></>}
  </section>{preview && <ReaderDrawer book={preview} onClose={() => setPreview(null)} />}</main>;
}

function LoadingResults() { return <div className="mt-8 grid gap-5" aria-live="polite"><p className="flex items-center gap-2 font-semibold"><Sparkles className="animate-pulse text-primary"/> Analysing your topics…</p>{[1,2,3].map(i => <div key={i} className="h-64 animate-pulse rounded-lg border border-border bg-background"><div className="m-6 h-5 w-2/5 rounded bg-muted"/><div className="m-6 h-3 w-3/5 rounded bg-muted"/></div>)}</div> }

function ReaderDrawer({ book, onClose }: { book: Book; onClose: () => void }) {
  const { selectedChapter: chapter, fontSize, setFontSize, theme, setTheme, bookmarked, setBookmarked, highlighted, setHighlighted, note, setNote } = useOnboarding();
  const navigate = useNavigate(); const [showNote, setShowNote] = useState(false);
  return <div className="fixed inset-0 z-50 bg-foreground/35" role="dialog" aria-modal="true" aria-label="Chapter preview"><div className={cn("absolute inset-y-0 right-0 flex w-full max-w-3xl flex-col shadow-2xl", theme === "paper" ? "bg-background" : theme === "sepia" ? "bg-sepia" : "bg-ink text-ink-foreground")}>
    <div className="flex h-16 items-center justify-between border-b border-border px-4"><button onClick={onClose} className="grid size-10 place-items-center rounded-md hover:bg-muted/50" aria-label="Close preview"><X size={21}/></button><p className="hidden truncate px-4 text-sm font-semibold sm:block">{book.title} · Chapter {chapter.number}</p><div className="flex items-center gap-1"><button aria-label="Decrease text size" onClick={() => setFontSize(Math.max(15, fontSize - 1))} className="tool-button"><Minus size={17}/></button><button aria-label="Increase text size" onClick={() => setFontSize(Math.min(24, fontSize + 1))} className="tool-button"><Plus size={17}/></button><button aria-pressed={bookmarked} aria-label="Bookmark chapter" onClick={() => setBookmarked(!bookmarked)} className={cn("tool-button", bookmarked && "text-primary")}><Bookmark size={18} fill={bookmarked ? "currentColor" : "none"}/></button><button aria-pressed={highlighted} aria-label="Highlight paragraph" onClick={() => setHighlighted(!highlighted)} className={cn("tool-button", highlighted && "text-warning")}><Highlighter size={18}/></button></div></div>
    <div className="flex items-center justify-between border-b border-border px-5 py-3"><div className="flex gap-1">{(["paper","sepia","ink"] as const).map(t => <button key={t} onClick={() => setTheme(t)} className={cn("size-7 rounded-full border-2", `theme-${t}`, theme === t ? "border-primary" : "border-border")} aria-label={`${t} reading theme`}/>)}</div><button onClick={() => setShowNote(!showNote)} className="text-sm font-semibold underline underline-offset-4">{showNote ? "Hide note" : "Add note"}</button></div>
    {showNote && <div className="border-b border-border p-4"><label htmlFor="reader-note" className="mb-2 block text-sm font-semibold">Your note</label><textarea id="reader-note" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Capture a thought about this paragraph…" className="w-full rounded-md border border-input bg-background p-3 text-foreground outline-none focus:ring-4 focus:ring-ring"/></div>}
    <div className="overflow-y-auto px-6 py-10 sm:px-14"><div className="mx-auto max-w-reading"><p className="text-xs font-bold uppercase text-primary">Chapter {chapter.number}</p><h2 className="mt-3 font-display text-4xl leading-tight">{chapter.title}</h2><p className="mt-3 text-sm opacity-60">Pages {chapter.pages}</p><p className={cn("mt-9 font-reading leading-[1.85]", highlighted && "rounded bg-highlight px-1 text-foreground")} style={{ fontSize }}>{chapter.preview}</p>
      <div className="relative mt-4 h-60 overflow-hidden" aria-hidden="true"><div className="space-y-4 opacity-20 blur-[1.5px]">{[1,2,3,4].map(i => <div key={i} className="h-4 rounded bg-current" style={{width: `${95 - i * 6}%`}}/>)}</div><div className="absolute inset-0 bg-gradient-to-b from-transparent to-[var(--reader-fade)]"/></div>
      <div className="relative z-10 -mt-20 rounded-lg border border-border bg-background p-6 text-center text-foreground shadow-warm-lg"><p className="font-ui text-xl font-bold">Keep your momentum</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Unlock the rest of this chapter and your personalised revision plan. Ready to study in under a minute.</p><Button className="mt-5" onClick={() => navigate({ to: "/signup" })}>Continue reading, start studying <ArrowRight size={17}/></Button></div>
    </div></div>
  </div></div>;
}

export function SignupPage() {
  const { selectedBook: book, selectedChapter: chapter, provider, setProvider, payment, setPayment, setSignedUp } = useOnboarding();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [course, setCourse] = useState(""); const [card, setCard] = useState(""); const [expiry, setExpiry] = useState(""); const [cvc, setCvc] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const navigate = useNavigate();
  const chooseProvider = (next: typeof provider) => { setProvider(next); if (next !== "email") { setName("Alex Morgan"); setEmail("alex.morgan@university.ac.uk"); setCourse(next === "unidays" ? "BSc Psychology" : course); } };
  const submit = (e: FormEvent) => { e.preventDefault(); if (!name || !email || !course || (payment === "card" && (!card || !expiry || !cvc))) { setError("Complete the highlighted details to continue."); return; } setError(""); setBusy(true); window.setTimeout(() => { setSignedUp(true); navigate({ to: "/study" }); }, 1000); };
  return <main className="min-h-screen bg-paper"><Header back="/results"/><div className="mx-auto grid max-w-6xl gap-10 px-5 pb-20 pt-7 lg:grid-cols-[0.85fr_1.15fr] lg:px-8">
    <aside className="lg:sticky lg:top-8 lg:self-start"><p className="text-sm font-semibold text-primary">Ready to study in under a minute</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">Your fastest route is ready.</h1><div className="mt-8 flex gap-5 border-y border-border py-6"><Cover book={book} small/><div><p className="font-ui text-lg font-bold">{book.title}</p><p className="mt-1 text-sm text-muted-foreground">Chapter {chapter.number}: {chapter.title}</p><p className="mt-3 flex items-center gap-2 text-sm"><Clock3 size={16}/> {chapter.minutes} min focused reading</p></div></div><ul className="mt-6 grid gap-3 text-sm">{["Full book and chapter access", "Your personalised revision plan", "Notes, highlights and bookmarks"].map(x => <li key={x} className="flex gap-2"><CheckCircle2 size={18} className="text-success"/>{x}</li>)}</ul></aside>
    <section className="rounded-lg border border-border bg-background p-5 shadow-warm sm:p-8"><h2 className="font-ui text-2xl font-bold">Start your student plan</h2><p className="mt-2 text-sm text-muted-foreground">14 days free, then £12 per month. Cancel anytime.</p>
      <div className="mt-6 grid gap-3"><Button size="lg" onClick={() => chooseProvider("unidays")} className={cn("relative", provider === "unidays" && "ring-4 ring-ring")}><span className="absolute left-4 rounded bg-background/20 px-2 py-0.5 text-[10px]">Student discount applied</span>Continue with UniDays</Button><div className="grid grid-cols-2 gap-3"><Button variant="outline" onClick={() => chooseProvider("google")} className={cn(provider === "google" && "border-primary ring-4 ring-ring")}>G&nbsp; Continue with Google</Button><Button variant="outline" onClick={() => chooseProvider("apple")} className={cn(provider === "apple" && "border-primary ring-4 ring-ring")}>●&nbsp; Continue with Apple</Button></div></div>
      <div className="my-7 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>or sign up with email<span className="h-px flex-1 bg-border"/></div>
      <form onSubmit={submit} noValidate><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" value={name} onChange={setName} placeholder="Alex Morgan"/><Field label="Email" type="email" value={email} onChange={setEmail} placeholder="you@university.ac.uk"/><label className="sm:col-span-2"><span className="field-label">University course</span><input list="courses" value={course} onChange={(e) => setCourse(e.target.value)} className="field" placeholder="Search courses…"/><datalist id="courses"><option>BSc Psychology</option><option>LLB Law</option><option>BA Economics</option><option>BSc Computer Science</option></datalist></label></div>
      <fieldset className="mt-7"><legend className="font-ui text-lg font-bold">Payment</legend><p className="mt-1 text-xs text-muted-foreground">Mock payment — no real charge will be made.</p><div className="mt-4 grid grid-cols-3 gap-2">{(["card","google","apple"] as const).map(method => <button type="button" key={method} onClick={() => setPayment(method)} className={cn("h-12 rounded-md border text-sm font-semibold", payment === method ? "border-primary bg-primary-soft text-primary" : "border-input")}>{method === "card" ? "Card" : method === "google" ? "G Pay" : "● Pay"}</button>)}</div>{payment === "card" && <div className="mt-4 grid grid-cols-2 gap-4"><div className="col-span-2"><Field label="Card number" value={card} onChange={setCard} placeholder="4242 4242 4242 4242"/></div><Field label="Expiry" value={expiry} onChange={setExpiry} placeholder="MM / YY"/><Field label="CVC" value={cvc} onChange={setCvc} placeholder="123"/></div>} {payment !== "card" && <div className="mt-4 rounded-md bg-muted p-4 text-sm">You’ll confirm this mock payment with {payment === "google" ? "Google Pay" : "Apple Pay"}. No account or charge is created.</div>}</fieldset>
      {error && <p className="mt-4 text-sm font-semibold text-destructive" role="alert">{error}</p>}<Button type="submit" size="lg" className="mt-6 w-full" disabled={busy}>{busy ? "Preparing your study plan…" : "Start studying now"}</Button><p className="mt-4 text-center text-xs text-muted-foreground">By continuing, you agree to this prototype’s mock terms.</p></form>
    </section></div></main>;
}

function Field({ label, value, onChange, placeholder, type="text" }: { label: string; value: string; onChange: (v: string) => void; placeholder: string; type?: string }) { return <label><span className="field-label">{label}</span><input className="field" type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}/></label>; }

export function StudyPage() {
  const { query, selectedBook: book, selectedChapter: chapter, topicStatus, cycleTopic } = useOnboarding(); const set = resultsFor(query); const topics = book.topics.filter(t => t.covered);
  return <main className="min-h-screen bg-paper"><Header/><section className="mx-auto max-w-7xl px-5 pb-20 pt-7 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Your study space</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">You know where to start.</h1></div><span className="rounded-full bg-warning-soft px-4 py-2 text-sm font-bold text-warning">Exam prep</span></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-12"><article className="relative overflow-hidden rounded-lg bg-foreground p-7 text-background lg:col-span-5"><p className="text-sm opacity-70">Time saved</p><p className="mt-2 font-display text-5xl">~6h 40m</p><p className="mt-5 max-w-md text-sm leading-6 opacity-75">Browsing manually: ~7h 30m → With Perlego: ~50m to find, ~4h of targeted reading.</p><div className="absolute -bottom-10 -right-5 font-display text-[150px] leading-none opacity-5">6h</div></article>
      <article className="rounded-lg border border-border bg-background p-6 lg:col-span-7"><p className="text-sm font-semibold text-primary">Continue studying</p><div className="mt-5 flex gap-5"><Cover book={book} small/><div className="flex flex-1 flex-col items-start"><h2 className="font-ui text-xl font-bold">Chapter {chapter.number}: {chapter.title}</h2><p className="mt-2 text-sm text-muted-foreground">{book.title} · p. {chapter.pages.split("–")[0]}</p><div className="mt-5 h-1.5 w-full overflow-hidden rounded-full bg-muted"><div className="h-full w-[18%] bg-primary"/></div><p className="mt-2 text-xs text-muted-foreground">18% complete · {chapter.minutes} min remaining</p><Button className="mt-auto" onClick={() => alert("Reader resumed — mock interaction")}>Continue reading <ArrowRight size={17}/></Button></div></div></article>
      {topics.length > 1 && <><article className="rounded-lg border border-border bg-background p-6 lg:col-span-7"><h2 className="font-ui text-xl font-bold">Topic coverage</h2><p className="mt-1 text-sm text-muted-foreground">Everything from your original search, mapped to a chapter.</p><div className="mt-5 divide-y divide-border">{topics.map((topic, i) => { const status = topicStatus[topic.label] ?? (i === 0 ? "In progress" : "Not started"); return <div key={topic.label} className="flex flex-wrap items-center gap-3 py-4"><span className={cn("grid size-8 place-items-center rounded-full", status === "Done" ? "bg-success text-primary-foreground" : "bg-muted text-muted-foreground")}>{status === "Done" ? <Check size={16}/> : i+1}</span><div className="min-w-48 flex-1"><p className="font-semibold">{topic.label}</p><p className="text-xs text-muted-foreground">Chapter {book.chapters[Math.min(i, book.chapters.length - 1)]?.number}: {book.chapters[Math.min(i, book.chapters.length - 1)]?.title}</p></div><span className="text-xs font-semibold text-muted-foreground">{status}</span><Button size="sm" variant="outline" onClick={() => cycleTopic(topic.label)}>{status === "Done" ? "Reset" : status === "In progress" ? "Mark done" : "Start"}</Button></div>})}</div></article>
      <article className="rounded-lg border border-border bg-background p-6 lg:col-span-5"><h2 className="font-ui text-xl font-bold">Your revision plan</h2><div className="mt-6 border-l-2 border-primary pl-5"><p className="text-xs font-bold uppercase text-primary">Day 1</p><h3 className="mt-2 font-semibold">Build the foundations</h3><p className="mt-1 text-sm text-muted-foreground">{book.chapters.slice(0,2).map(c => `Ch. ${c.number}`).join(" + ")} · 2 focused sessions</p><p className="mt-2 text-sm font-semibold">1h 20m</p></div><div className="mt-7 border-l-2 border-border pl-5"><p className="text-xs font-bold uppercase text-muted-foreground">Day 2</p><h3 className="mt-2 font-semibold">Recall and connect</h3><p className="mt-1 text-sm text-muted-foreground">Finish targeted reading + 25 min recall</p><p className="mt-2 text-sm font-semibold">1h 05m</p></div></article></>}
    </div><p className="mt-6 text-center text-xs text-muted-foreground">Plan based on {set.shortLabel.toLowerCase()} topics and an average reading pace.</p></section></main>;
}