import { useEffect, useRef } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { ArrowRight, Bookmark, Highlighter, Minus, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Header } from './perlego';
import { useOnboarding } from '@/lib/onboarding-context';
import { chapterParagraphs, chapterTopics, matchedChapters, resultSets } from '@/lib/mock-data';
import { cn } from '@/lib/utils';

export function ReaderPage({preview=false}:{preview?:boolean}) {
 const s=useOnboarding();const navigate=useNavigate();const scroll=useRef<HTMLDivElement>(null);
 const book=s.selectedBook, chapter=s.selectedChapter;
 const unlocked=s.signedUp&&!preview;
 const paragraphs=chapterParagraphs(book,chapter);
 useEffect(()=>{if(s.hydrated&&scroll.current)scroll.current.scrollTop=s.position;},[s.hydrated,book.id,chapter.number]);
 const chapters=matchedChapters(book,s.topics);const choices=chapters.length?chapters:book.chapters;
 return <main className={cn('min-h-screen',s.theme==='ink'?'bg-ink text-ink-foreground':s.theme==='sepia'?'bg-sepia':'bg-background')}><Header back={preview?'/results':'/study'}/><div className="mx-auto max-w-5xl border-y border-border px-5 py-3"><div className="flex flex-wrap items-center justify-between gap-3"><label className="min-w-0 max-w-full"><span className="sr-only">Chapter</span><select className="field max-w-full" value={chapter.number} onChange={e=>{const next=book.chapters.find(c=>c.number===Number(e.target.value));if(next)s.selectBook(book,next);}}>{choices.map(c=><option key={c.number} value={c.number}>Chapter {c.number}: {c.title}</option>)}</select></label><div className="flex flex-wrap gap-1">{[{label:'Decrease text size',Icon:Minus,action:()=>s.setFontSize(Math.max(15,s.fontSize-1))},{label:'Increase text size',Icon:Plus,action:()=>s.setFontSize(Math.min(24,s.fontSize+1))},{label:'Bookmark chapter',Icon:Bookmark,action:()=>s.setBookmarked(!s.bookmarked),active:s.bookmarked},{label:'Highlight paragraph',Icon:Highlighter,action:()=>s.setHighlighted(!s.highlighted),active:s.highlighted}].map(tool=><Button key={tool.label} variant="ghost" size="icon" title={tool.label} aria-label={tool.label} aria-pressed={tool.active} onClick={tool.action} className={tool.active?'bg-primary-soft text-primary':''}><tool.Icon size={18}/></Button>)}{(['paper','sepia','ink'] as const).map(theme=><Button key={theme} variant="outline" size="icon" title={`${theme} reading theme`} aria-label={`${theme} reading theme`} aria-pressed={s.theme===theme} onClick={()=>s.setTheme(theme)} className={cn('size-8 rounded-full border-2',`theme-${theme}`,s.theme===theme?'border-primary':'border-border')}/>)}</div></div></div>
 <div ref={scroll} className="h-[calc(100dvh-180px)] min-h-96 overflow-y-auto" onScroll={e=>{if(unlocked)s.setPosition(e.currentTarget.scrollTop);}}><article className="mx-auto max-w-reading px-5 py-10 sm:px-8"><p className="text-sm opacity-70">{book.title} · Original sample text</p><h1 className="mt-4 font-display text-4xl leading-tight">{chapter.title}</h1><p className="mt-3 text-sm opacity-70">Chapter {chapter.number} · pp. {chapter.pages} · {chapter.minutes} min estimated</p>{unlocked&&<div className="my-6 flex flex-wrap items-center gap-4"><Button onClick={s.startSession} disabled={s.status!=='Not started'}>{s.status==='Not started'?'Start study session':s.status==='Done'?'Chapter complete':'Session in progress'}</Button><span className="text-sm" aria-live="polite">{s.status}</span></div>}
  {(unlocked?paragraphs:paragraphs.slice(0,1)).map((text,i)=><p key={i} className={cn('mt-7 font-reading leading-[1.85]',i===0&&s.highlighted&&'bg-highlight text-foreground')} style={{fontSize:s.fontSize}}>{text}</p>)}
  {!unlocked&&<div className="relative" aria-hidden="true"><div className="pointer-events-none select-none" style={{maskImage:'linear-gradient(to bottom, black 0%, transparent 90%)',WebkitMaskImage:'linear-gradient(to bottom, black 0%, transparent 90%)'}}>{paragraphs.slice(1,5).map((text,i)=><p key={i} className="mt-7 font-reading leading-[1.85]" style={{fontSize:s.fontSize,opacity:0.55-i*0.13}}>{text}</p>)}</div></div>}
  {!unlocked&&<section className="-mt-20 border-t border-border py-8"><h2 className="font-ui text-xl font-bold">Keep your momentum</h2><p className="mt-3 text-sm opacity-70">Unlock this chapter and your personalised revision plan.</p><Button className="mt-5 max-w-full whitespace-normal" onClick={()=>{s.addBook(book);navigate({to:s.signedUp?'/reader':'/signup'});}}>{s.signedUp?'Open full chapter':'Continue reading, start studying'} <ArrowRight size={17}/></Button></section>}
 <label className="mt-8 block"><span className="field-label">Your chapter note</span><textarea className="min-h-24 w-full rounded-md border border-input bg-background p-3 text-foreground focus:ring-4 focus:ring-ring" value={s.note} onChange={e=>s.setNote(e.target.value)} placeholder="Capture a thought…"/></label>
 {unlocked&&<div className="mt-8 flex flex-wrap gap-3"><Button disabled={s.status==='Not started'||s.status==='Done'} onClick={s.completeChapter}>Mark chapter complete</Button><Button variant="outline" onClick={()=>navigate({to:'/study'})}>Back to dashboard</Button></div>}
 </article></div></main>
}

export function StudyDashboard(){
 const s=useOnboarding();const navigate=useNavigate();
 const books=resultSets.flatMap(set=>set.books).filter(b=>s.plan.includes(b.id));
 const sessions=books.flatMap(book=>matchedChapters(book,s.topics).map(chapter=>({book,chapter,key:`${book.id}:${chapter.number}`})));
 const days=Math.max(1,Math.ceil((new Date(s.examDate+'T23:59:59').getTime()-Date.now())/86400000)||1);
 const total=sessions.reduce((n,x)=>n+x.chapter.minutes,0); const done=sessions.filter(x=>s.chapters[x.key]?.status==='Done').length;
 const resume=sessions.find(x=>x.book.id===s.selectedBook.id&&x.chapter.number===s.selectedChapter.number&&s.chapters[x.key]?.status!=='Done')??sessions.find(x=>s.chapters[x.key]?.status!=='Done')??sessions[0];
 return <main className="min-h-screen bg-paper"><Header/><section className="mx-auto max-w-6xl px-5 pb-20 pt-8 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Your study space</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Your revision plan</h1></div>{s.examDate && <span className="text-sm text-muted-foreground">Exam: {s.examDate}</span>}</div>
 <div className="mt-8 grid gap-7 border-y border-border py-8 sm:grid-cols-2"><div><p className="text-sm text-muted-foreground">Focused reading estimate</p><p className="mt-2 font-display text-4xl">{total} minutes</p><p className="mt-3 text-sm text-muted-foreground">{sessions.length} targeted chapters{s.examDate && <> · {days} {days===1?'day':'days'} available</>}</p><p className="mt-3 text-sm">{done} of {sessions.length} chapters complete</p><progress className="mt-3 h-2 w-full accent-primary" value={done} max={sessions.length||1}/></div><div><p className="text-sm font-semibold text-primary">Continue studying</p>{resume?<><h2 className="mt-3 font-ui text-xl font-bold">{resume.chapter.title}</h2><p className="mt-2 text-sm text-muted-foreground">{resume.book.title} · Chapter {resume.chapter.number}</p><Button className="mt-5" onClick={()=>{s.selectBook(resume.book,resume.chapter);navigate({to:s.signedUp?'/reader':'/signup'});}}>Continue reading <ArrowRight size={18}/></Button></>:<><p className="mt-3">Your revision plan is empty.</p><Button className="mt-4" onClick={()=>navigate({to:'/results'})}>Find relevant books</Button></>}</div></div>
 <div className="mt-8 flex items-center justify-between gap-3"><h2 className="font-ui text-xl font-bold">Your books</h2><Button variant="ghost" onClick={()=>navigate({to:'/results'})}>Add a book <Plus size={17}/></Button></div><div className="mt-4 grid gap-3">{books.map(book=><article key={book.id} className="flex flex-wrap items-center justify-between gap-4 rounded-lg border border-border bg-background p-5"><div><h3 className="font-semibold">{book.title}</h3><p className="mt-1 text-sm text-muted-foreground">{matchedChapters(book,s.topics).length} relevant chapters · {book.author}</p></div><Button variant="ghost" onClick={()=>s.toggleBook(book)}>Remove from plan</Button></article>)}</div>
 {s.topics.length>1&&<section className="mt-10"><h2 className="font-ui text-xl font-bold">Topic coverage</h2><div className="mt-4 divide-y divide-border">{s.topics.map(topic=>{const linked=sessions.filter(x=>chapterTopics(x.book,x.chapter).includes(topic));const status=linked.length&&linked.every(x=>s.chapters[x.key]?.status==='Done')?'Done':linked.some(x=>s.chapters[x.key]?.status==='In progress'||s.chapters[x.key]?.status==='Done')?'In progress':'Not started';return <div key={topic} className="flex flex-wrap justify-between gap-3 py-4"><div><p className="font-semibold">{topic}</p><p className="mt-1 text-sm text-muted-foreground">{linked.length?linked.map(x=>`${x.book.title}, Ch. ${x.chapter.number}`).join(' · '):'No matching chapter in your plan'}</p></div><span className="text-sm text-muted-foreground">{linked.length?status:'Not covered'}</span></div>})}</div></section>}
 <section className="mt-10"><h2 className="font-ui text-xl font-bold">Study sessions</h2><div className="mt-4 divide-y divide-border">{sessions.map((session,i)=><div key={session.key} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="text-xs font-bold text-primary">{s.examDate ? `Day ${Math.min(days,1+Math.floor(i*days/Math.max(1,sessions.length)))}` : `Session ${i+1}`}</p><h3 className="mt-2 font-semibold">{session.chapter.title}</h3><p className="mt-1 text-sm text-muted-foreground">{session.chapter.minutes} min · {s.chapters[session.key]?.status??'Not started'}</p></div><Button variant="outline" onClick={()=>{s.selectBook(session.book,session.chapter);navigate({to:s.signedUp?'/reader':'/signup'});}}>Open chapter</Button></div>)}</div></section>
 </section></main>
}
